words = {'python': '大蟒蛇', 'list': '列表', 'tuple': '元组', 'string': '字符串', 'dict ': '双关语，字典', 'integer': '整数',
         'float': '浮动', 'date': '日期', 'time': '时间', 'set': '设置，集合', 'number': '数字', 'path': '路径', 'import ': '输入',
         'from': '从，来自', 'with': '和', 'and': '且', 'or': '或', 'not': '不', 'is': '是', 'True': '真', 'False': '假',
         'if': '如果', 'else': '否则', 'for': '由于', 'while': '在......期间', 'try': '尝试', 'except': '除…以外', 'finally': '最后',
         'bool': '布尔', 'in': '在....里 ', 'class': '类', 'function': '函数', 'print': '打印', 'generator': '生成器',
         'globe': '全局', 'return': '返回', 'json': '数据', 'open': '打开', 'as': '作为', 'project': '项目', 'package': '包',
         'file': '文件', '': '', 'django': '', 'url': '路由', 'view': '视图', 'model': '模型', 'manage': '管理', 'template': '模板',
         'static': '静止的', 'serializer': '可序列化的', 'request': '请求', 'response': '响应', 'migration': '迁移', 'path ': ' 路径',
         'class ': ' 类', 'public ': ' 公共的,公用的', 'private ': ' 私有的,私人的', 'static ': ' 静态', 'void ': ' 空的,没有返回值的',
         'main ': ' 主要的,重要的', 'system ': ' 系统', 'out ': ' 往外,出现,出外', 'print ': ' 打印', 'demo ': ' 演示，例子',
         'define ': ' 定义', 'syntax ': ' 语法', 'invalid ': ' 无效的', 'indentation ': ' 缩进', 'unexpected ': ' 不期望的',
         'usage ': ' 使用', 'version ': ' 版本', 'author ': ' 作者', 'int ': ' 整型', 'long ': ' 长整形', 'char ': ' 字符型',
         'string ': ' 字符串类型', 'float ': ' 单精度浮点类型', 'type ': ' 类型', 'bool ': ' 布尔类型，真假', 'True ': ' 真，正确的(成立的)',
         'False ': ' 假，错误的(不成立的)', 'encode ': ' 编码', 'decode ': ' 解码', 'integrated ': ' 集成', 'development ': ' 开发',
         'environment ': ' 环境', 'count ': ' 计数；计算', 'sum ': ' 总数,总计', 'salary ': ' 薪水', 'random ': ' 随机的', 'if ': ' 如果',
         'else ': ' 否则', 'switch ': ' 判断语句', 'case ': ' 实例,情况', 'break ': ' 退出', 'continue ': ' 跳出...继续',
         'return ': ' 返回', 'default ': ' 默认的', 'while ': ' 当……的时候', 'interpreter ': ' 解释器', 'configured ': ' 配置',
         'variables ': ' 变量', 'unreachable ': ' 不能达到的', 'colum ': ' 列', 'row ': ' 行', 'index ': ' 角标,索引,指针',
         'max ': ' 最大的', 'min ': ' 最小的', 'function ': ' 功能,函数', 'method ': ' 方法', 'result ': ' 结果', 'compare ': ' 比较',
         'temp ': ' 临时工', 'null ': ' 空,无效的', 'exception ': ' 异常', 'error ': ' 错误', 'out of ': ' 在...之外',
         'length ': ' 长度', 'sort ': ' 将...排序', 'change ': ' 改变，交换', 'swap ': ' 交换', 'half ': ' 一半的,半个的',
         'search ': ' 搜索,查找', 'mid ': ' 中间的', 'number ': ' 数字,号码', 'transition ': '', 'object ': ' 对象, 物体',
         'class member ': ' 类成员', 'class method ': ' 类方法', 'package ': ' 包', 'car ': ' 汽车,小轿车', 'color ': ' 颜色',
         'red ': ' 红色', 'blue ': ' 蓝色', 'black ': ' 黑色', 'white ': ' 白色', 'run ': ' 跑, 运行', 'person ': ' 人',
         'people ': ' 人,人们', 'age ': ' 年龄', 'name ': ' 名字,名称,名誉,名人', 'speak ': ' 说话,讲话,', 'set ': ' 设置',
         'reset ': ' 重新设置', 'get ': ' 获取,获得', 'multiply ': ' 乘', 'division ': ' 除法', 'iterable ': ' 可迭代的',
         'attribute ': ' 属性', 'code ': ' 代码,代号,编码', 'country ': ' 国家,国土', 'university ': ' 大学', 'college ': ' 大学',
         'show ': ' 显示,展示', 'sleep ': ' 睡, 睡觉, 睡眠 1秒=1000毫秒', 'single ': ' 单一的,单独的,单身的,单程的', 'instance ': ' 实例,情况',
         'tool ': ' 工具', 'data ': ' 资料', 'develop ': ' 开发', 'extends ': ' 继承,延伸,推广', 'phone ': ' 电话',
         'call ': ' 呼叫,给...打电话', 'study ': ' 学习,研究', 'work ': ' 工作,操作', 'location ': ' 位置(文件在电脑中的位置)',
         'encoding ': ' 编码', 'super ': ' 父类的,超级的,,超类的', 'final ': ' 最终的', 'finally ': ' 最后,最终', 'interface ': ' 接口',
         'implements ': ' 实现', 'mouse ': ' 鼠标, 老鼠', 'bonus ': ' 奖金', 'inner ': ' 内部的', 'protect ': ' 保护，受保护的， 防卫',
         'file ': ' 文件', 'folder ': ' 文件夹', 'view ': ' 视图, 视线,看', 'equals ': '判断两个字符串是否相等', 'memory ': ' 记忆，内存，存储器',
         'heap ': ' 堆', 'space ': ' 空间', 'throw ': ' 抛出,投掷', 'message ': ' 消息,信息,通知', 'try ': ' 尝试,试图',
         'catch ': ' 捕获,捕捉,抓住', 'close ': ' 关闭,结束', 'open ': ' 打开,公开', 'add ': ' 增加', 'edit ': ' 编辑',
         'project ': ' 项目,工程,计', 'directory ': ' 目录', 'runtime ': ' 运行时间', 'current ': ' 当前的,现在的',
         'preference ': ' 个人喜好', 'rename ': ' 重命名', 'template ': ' 模板', 'runnable ': ' 可捕捉的',
         'interrupted ': ' 中断的,被阻止的', 'ticket ': ' 票', 'bank ': ' 银行', 'tank ': ' 坦克', 'flag ': ' 标记, 旗帜',
         'dead ': ' 死亡的,无生命的', 'lock ': ' 锁', 'unlock ': ' 解锁', 'console ': ' 控制台', 'font ': ' 字体', 'resource ': ' 资源',
         'notify ': ' 唤醒, 告知', 'input ': ' 输入', 'output ': ' 输出', 'bounded ': ' 有界限的', 'buffer ': ' 缓冲区',
         'signal ': ' 信号,标志', 'condition ': ' 条件', 'producer ': ' 生产者', 'consumer ': ' 消费者', 'substring ': ' 子字符串',
         'append ': ' 添加', 'insert ': ' 插入', 'delete ': ' 删除', 'replace ': ' 代替,取代,更换', 'update ': ' 更新',
         'create ': ' 创造,创作', 'builder ': ' 构建器', 'character ': ' 字符', 'reverse ': ' 反转,翻转', 'collection ': ' 集合,聚集,采集',
         'remove ': ' 移除,删除', 'clear ': ' 清空,清除,清楚的.', 'iterator ': ' 迭代器', 'list ': ' 列表,清单(集合之一)'}

