# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='modelNum',
            field=models.CharField(default='0000-0000', max_length=45),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.IntegerField(default='0'),
        ),
    ]
